export const PATHS = {
  LOGIN: '/login',
  REGISTER: '/register',
  PRODUCT: '/product',
  FEATURES: '/features',
  USE_CASES: '/use-cases',
  DASHBOARD: '/tool/dashboard',
  PROJECT_DETAIL: '/tool/projects/:id',
  PROJECT_EXECUTIONS: '/tool/projects/:id/executions',
  WORKFLOWS: '/tool/workflows',
  CREATE_WORKFLOW: '/tool/workflows/new',
  WORKFLOW_DETAIL: '/tool/workflows/:id',
  EXECUTIONS: '/tool/executions',
  LOGS: '/tool/logs',
  SETTINGS: '/tool/settings',
  CONTACT: '/contact',
  SHORTCUTS: '/tool/shortcuts',
  WORKFLOW_BUILDER: '/tool/builder',
};
